// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4UH3bSE0x3-sqJ7zZ4UqpOiCHHkMcZRI',
    appId: '1:461209226052:web:5fa96fab3cbffafae6a511',
    messagingSenderId: '461209226052',
    projectId: 'cylinders-53542',
    authDomain: 'cylinders-53542.firebaseapp.com',
    storageBucket: 'cylinders-53542.appspot.com',
    measurementId: 'G-9DEL4JK29Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsi8GCgKO_8iAQwYguNJfJTuaBV2NqjuQ',
    appId: '1:461209226052:android:0f6c2ccd7d1b9c00e6a511',
    messagingSenderId: '461209226052',
    projectId: 'cylinders-53542',
    storageBucket: 'cylinders-53542.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKycnS99sHg1WEECz05Q4iO07Z6e9-ofE',
    appId: '1:461209226052:ios:b68eecda22955426e6a511',
    messagingSenderId: '461209226052',
    projectId: 'cylinders-53542',
    storageBucket: 'cylinders-53542.appspot.com',
    iosClientId: '461209226052-9hi4car3vkmvoeqsf6poajb6eopi11s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cylinders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKycnS99sHg1WEECz05Q4iO07Z6e9-ofE',
    appId: '1:461209226052:ios:1f34a994c358e4ede6a511',
    messagingSenderId: '461209226052',
    projectId: 'cylinders-53542',
    storageBucket: 'cylinders-53542.appspot.com',
    iosClientId: '461209226052-ijrs3bckmieodoi6btvb6llidpfgv4an.apps.googleusercontent.com',
    iosBundleId: 'com.example.cylinders.RunnerTests',
  );
}
